GET http://127.0.0.1:8889/hello

### get the all recipes
GET http://127.0.0.1:8889/recipe/list

###
GET http://127.0.0.1:8889/recipe/searchByName?name=Sandwich

###
GET http://localhost:8889/recipe/searchById?id=1

###
GET http://127.0.0.1:8889/recipe/searchByIngredient?ingredients=cabbage

###
GET http://127.0.0.1:8889/recipe/searchByIngredient?ingredients=Eggs,Butter

###
GET http://127.0.0.1:8889/recipe/searchByIngredient?ingredients=Eggs,Mayonnaise,Lettuce

###
GET http://localhost:8889/recipe/getRandomRecipes

###
GET http://localhost:8889/recipe/advancedSearch?necessary=Eggs,Mayonnaise,Lettuce&option=Vinegar,Steaks,Onion

###
GET http://localhost:8889/recipe/advancedSearch?necessary=Eggs,Mayonnaise&option=Steaks

###
GET http://localhost:8889/recipe/advancedSearch?necessary=toast&option=butter

###
GET http://localhost:8889/ingredient/searchSubstitution?name=butter

###
GET http://localhost:8889/ingredient/getAllSubstitutionList
